prode/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from . import views
from .models import Bet

app_name = 'prode'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', auth_views.login, {'template_name': 'prode/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('home/', login_required(views.HomeView.as_view()), name='home'),
    path('home/apuestas', login_required(views.BetView.as_view()), name='apuestas'),
    path('home/datos', login_required(views.MyDataView.as_view()), name='datos'),
    path('home/puntaje', login_required(views.ScoreView.as_view()), name='puntaje'),
    path('home/change_password/', views.change_password, name="change_password"),
    path('validate_username/', views.validate_username, name='validate_username'),
    # path('home/grupos', login_required(views.GroupView.as_view()), name='grupos'),
    ] 

prodesama/urls.py
from django.contrib import admin
from django.urls import path, include
from prode import views as prodeViews

urlpatterns = [
    path('', include('prode.urls')), 
    path('admin/', admin.site.urls),
]

prode/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils import timezone
from datetime import timedelta


class Team(models.Model):
    name = models.CharField(max_length=50)
    flag = models.ImageField(upload_to='prode/images/flags/')
    
    def team_matches(self):
        self.matches.all()
    
    def __str__(self):
        return self.name


class Competition(models.Model):
    name = models.CharField(max_length=100)
    available = models.BooleanField(default=False)

    def __str__(self):
        return (str(self.name))


class Match(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()
    team1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches')
    team2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matchs')
    team1_score = models.PositiveIntegerField(default=0)
    team2_score = models.PositiveIntegerField(default=0)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, null=True)
    def end_match(self):
        now = timezone.now() 
        return self.end <= now

    def get_endscore(self):
        winner = None
        if (self.end_match() == True):
            if (self.team1_score > self.team2_score):
                winner = self.team1
            elif (self.team1_score < self.team1_score):
                winner = self.team2
            elif (self.team1_score == self.team2_score):
                winner = "tie"
        return winner

    def is_unavailable(self):
        now = timezone.now()
        start = self.start - timedelta(hours=1)
        return now >= start

    def get_team1_matches(self):
        matches = list(Match.objects.all())
        team_matches = []
        for match in matches:
            if match.id != self.id and match.end_match():
                if match.team1 == self.team1 or match.team2 == self.team1:
                    team_matches.append(match)
        return team_matches

    def get_team2_matches(self):
        matches = list(Match.objects.all())
        team_matches = []
        for match in matches:
            if match.id != self.id and match.end_match():
                if match.team1 == self.team2 or match.team2 == self.team2:
                    team_matches.append(match)
        return team_matches

    def __str__(self):
        return (self.team1.name + " - " + self.team2.name)
        
        
class Bet(models.Model):
    user = models.ForeignKey(User, related_name='bets', blank=True, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE, related_name='bets') 
    team1_score = models.PositiveIntegerField(default=0)
    team2_score = models.PositiveIntegerField(default=0)
    result = models.PositiveIntegerField(default=0, null=True)
    calculated = models.BooleanField(default=False)

    def get_result(self):
            if (self.match.get_endscore() == self.match.team1) and (self.team1_score > self.team2_score):
                self.result = 1
            elif (self.match.get_endscore() == self.match.team2) and (self.team2_score > self.team1_score):
                self.result = 1
            elif (self.match.end_match()==True) and (self.match.team1_score == self.team1_score) and (self.match.team2_score == self.team2_score):
                self.result = 3
            elif (self.match.get_endscore() == "tie") and (self.team1_score == self.team2_score):
                self.result = 1
            else: 
                self.result = 0
            return self.result
    class Meta:
        unique_together = ('user', 'match')

    def __str__(self):
        return (str(self.match))


class CompetitionStat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comps')
    score = models.PositiveIntegerField(default=0)
    ranking = models.PositiveIntegerField(null=True)
    comp = models.ForeignKey(Competition, on_delete=models.CASCADE, null=True, related_name='comps')

    def get_score(self):
        lista = [self.user.bets.all()] 
        for elem in lista:
            for i in elem:
                if (self.comp == i.match.competition):
                    if i.calculated == False and i.match.end_match() == True:
                        self.score += i.result
                        i.calculated = True
                        i.save()
        return self.score

    def get_ranking(self):
        comp_stats = CompetitionStat.objects.filter(comp=self.comp).order_by('-score')
        lista = [cs for cs in comp_stats]
        for elem in lista:
            if (elem.user == self.user):
                self.ranking = lista.index(elem) + 1
        return self.ranking

    def __str__(self):
        return(str(self.user) + " - " + str(self.comp))

    class Meta:
        unique_together = ('user', 'comp')

prode/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Bet, Match

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']  #cleaned_data me asegura que no se escriba sql por ejemplo
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class BetForm(forms.ModelForm):
    team1_score = forms.IntegerField()
    team2_score = forms.IntegerField()
    match = forms.ModelChoiceField(queryset=Match.objects.only('id'))
    class Meta:
        model = Bet
        fields = ('team1_score', 'team2_score', 'match')

prode/views.py
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic    #TemplateView
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from prode.forms import RegistrationForm
from .models import Team, Match, Bet, Competition, CompetitionStat
from .forms import BetForm
from django.utils import timezone
import datetime
from datetime import timedelta
import json


def signup(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(reverse('prode:home'))
        else:
            messages.error(request, _('Ingresaste mal algún dato, volvé a registrarte.'))
            return redirect('prode:index')
    else:
        form = RegistrationForm()
    return render(request, 'prode/signup.html', {'form': form})


@login_required
def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'Ese nombre de usuario ya está registrado. Ingrese otro.'
    return JsonResponse(data)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _('Tu contraseña ha sido modificada'))
            return redirect('prode:datos')
        else:
            messages.error(request, _('Las contraseñas deben coincidir.'))
            return redirect('prode:datos')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'prode/change_password.html', {'form': form})


class IndexView(generic.ListView):
    template_name = 'prode/index.html'
    
    def get(self, request):
        matches = Match.objects.filter(competition__available=True).filter(end__gte=timezone.now()).order_by('start')[:4]
        comp_stats = CompetitionStat.objects.filter(ranking__lte=5).order_by('ranking')
        competition = Competition.objects.filter(available=True)
        args = {'matches': matches, 'competition':competition ,'comp_stats': comp_stats}
        return render(request, self.template_name, args)


class HomeView(generic.ListView):
    template_name = 'prode/home.html'
    def get(self, request):
        return render(request, self.template_name)


class BetView(generic.DetailView):
    template_name = 'prode/apuestas.html'

    def get(self, request):
        form = BetForm()
        m = Match.objects.filter(competition__available=True).order_by('start')
        matchs = []
        for i in m:
            if i.is_unavailable() == False:
                matchs.append(i)
        bets = Bet.objects.all()
        competitions = Competition.objects.filter(available=True)
        args = {'form': form, 'matchs': matchs[:10], 'bets': bets,
                'competitions': competitions}
        return render(request, self.template_name, args)

    def post(self, request):
        bet_id = request.POST.get("bet_id")
        if bet_id and request.user.bets.get(id=bet_id):
            bet = Bet.objects.get(id=bet_id)
            form = BetForm(request.POST, instance=bet)
        else:
            form = BetForm(request.POST)
        if form.is_valid():
            bet = form.save(commit=False)
            bet.user = request.user
            bet.save()
            team1_score = form.cleaned_data.get('team1_score')
            team2_score = form.cleaned_data.get('team2_score')
            match = form.cleaned_data.get('match')
            form = BetForm()
            if request.user.comps.exists()==False:
                cs = CompetitionStat()
                cs.user = request.user
                cs.comp = Competition.objects.get(name="Copa Libertadores")
                cs.save()
            messages.info(request, "Apuesta realizada!")
            return redirect ('prode:apuestas')
        args = {'form': form, 'team1_score': team1_score, 'team2_score': team2_score, 'match': match}
        return render(request, self.template_name, args)


class ScoreView(generic.DetailView):
    template_name = 'prode/puntaje.html'
    def get(self, request):
        comps = Competition.objects.filter(available=True)
        comp_stats = CompetitionStat.objects.all()
        bets = list(Bet.objects.all())
        bets.reverse()
        return render(request, self.template_name, {'comps':comps,'comp_stats':comp_stats, 'bets':bets})


class MyDataView(generic.DetailView):
    template_name = 'prode/datos.html'
    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        user_id = request.POST.get("user_id")
        if user_id:
            user = User.objects.get(pk=user_id)
            user.first_name = request.POST["first_name"]
            user.last_name = request.POST["last_name"]
            user.username = request.POST["username"]
            user.save()
            messages.success(request, 'Tus datos se han modificado', extra_tags='alert')
            return redirect('prode:datos')
        return render(request, self.template_name)

# class GroupView(generic.DetailView):
#     template_name = 'prode/grupos.html'
#     def get(self, request):
#         return render(request, self.template_name)

prode/templates/prode/apuestas.html
{% extends "prode/navigation.html" %}
{% load static %}
{% block content %}

<style>
    .carousel-control-prev,
    .carousel-control-next {
        margin-top: 15%;
        position: fixed;
        margin-left: 20%;
    }
</style>


    
<div id="betsCarousel" class="carousel slide" data-ride="carousel" data-interval="false">

    <div class="carousel-inner">
        {% for c in competitions %}        

            {% if forloop.first %}
                <div class="carousel-item active">
            {% else %}
                <div class="carousel-item">
            {% endif %}    
                
            <h1 class="text-light text-center">
                <div id="competitionTitle">
                    {{c.name}}
                </div>
            </h1>
            <br>
      
                    <div class="row text-center">

                        <div class="col-md-6 offset-md-3">
                            
                            <div class="lista-apuestas">
                            {% for match in matchs %}

                                {% if c.name == match.competition.name %}
                                {% include 'prode/messages.html' %}
                                    <form class="form-apuestas" method="POST" action="{% url 'prode:apuestas' %}">
                                        {% csrf_token %}
                                        {% for bet in bets %}
                                            {% if match.id == bet.match.id and bet.user == user %}
                                                <input type="hidden" name="bet_id" id="bet_id" value="{{ bet.id }}" formmethod="GET">
                                            {% endif %}
                                        {% endfor %}
                                        <input type="hidden" name="match" id="match" value="{{ match.id }}">

                                            <div id="accordionBet">
    
                                                <div class="card">                                                    
                                                    <div class="card-header" id="heading{{match.id}}" style="background: rgb(76, 167, 65)">
                                                        <h5 class="mb-0">
                                                            <button class="btn btn-link text-white" aria-expanded="false" type="button" data-toggle="collapse" data-target="#collapse{{match.id}}" aria-controls="collapse{{match.id}}">
                                                                {{ match }} | {{ match.start|date:'d-m-Y' }}
                                                                <i class="material-icons vertical-align-middle padding-bottom-3">
                                                                    expand_more
                                                                </i>
                                                            </button>
                                                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#betModal{{match.id}}">
                                                                <i class="material-icons vertical-align-middle padding-bottom-3">
                                                                    info
                                                                </i>
                                                            </button>
                                                        </h5>   
                                                    </div> <!--FIN CARD-HEADER-->
                                                    
                                                    <div id="collapse{{match.id}}" class="collapse" aria-labelledby="heading{{match.id}}" data-parent="#accordionBet">
                                                            
                                                        <div class="card-body">
                                                            <div class="row">
                                                                <div class="col">
                                                                    <img src="{{ '/static/' }}{{ match.team1.flag }}" alt="Bandera">
                                                                    <br>
                                                                    {{ match.team1.name }}
                                                                </div>
                                                                <div class="col">
                                                                    <input type="number" name="team1_score" class="form-control text-center" placeholder="Goal" min="0" max="15" required="" id="id_team1_score"
                                                                    {% for bet in bets %} {% if match.id == bet.match.id and bet.user == user %} value="{{bet.team1_score}}" {% endif %} {% endfor %}>
                                                                </div>
                                                                <div class="col">
                                                                    <input type="number" name="team2_score" class="form-control text-center" placeholder="Goal" min="0" max="15" required="" id="id_team2_score"
                                                                    {% for bet in bets %} {% if match.id == bet.match.id and bet.user == user %} value="{{bet.team2_score}}" {% endif %} {% endfor %}>
                                                                </div>
                                                                <div class="col">
                                                                    <img src="{{ '/static/' }}{{ match.team2.flag }}" alt="Bandera">
                                                                    <br>
                                                                    {{ match.team2.name }}
                                                                </div>
                                                            </div> <!-- FIN ROW -->
                                                                <button id="btn-apostar"class="btn btn-success" type="submit">Apostar</button>
                                                        </div> <!-- FIN CARD-BODY -->
                                                    
                                                    </div> <!-- FIN COLLAPSE -->
                                                
                                                </div> <!-- FIN CARD -->
                                    
                                            </div> <!-- FIN ACCORDION -->
                                        
                                    
                                    </form>
                                    <br>
                                

                                {% endif %}

                            {% endfor %} <!-- end matchs for -->
                            </div> <!-- FIN LISTA-APUESTAS -->
                        </div> <!-- FIN COL -->
                    
                    </div> <!-- FIN ROW -->

                </div> <!-- FIN CAROUSEL-ITEM -->
        
        {% endfor %} <!-- end competitions for -->
    
    {% if competitions|length > 1 %}
    </div> <!-- FIN CAROUSEL INNER -->
    <a class="carousel-control-prev" href="#betsCarousel" role="button" data-slide="prev">
        <i class="material-icons" style="font-size: 400px; color: white">
            arrow_left
        </i>
    </a>
    
    <a class="carousel-control-next" href="#betsCarousel" role="button" data-slide="next">
        <i class="material-icons" style="font-size: 400px; color: white">
            arrow_right
        </i>
    </a>
    {% endif %}
</div> <!-- FIN CAROUSEL -->

<!-- Modal -->
{% for match in matchs %}
<div class="modal fade" id="betModal{{match.id}}" tabindex="-1" role="dialog" aria-labelledby="betModal{{match.id}}Label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">  
        <div class="modal-content">
            <div class="modal-header" id="betModalHeader">
                <h5 class="modal-title" id="betModal{{match.id}}Label">{{match}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row text-center">
                    <div class="col">
                        <h5><b><u>{{ match.team1 }}</u></b></h5>
                        <br>
                        <table class="table">
                            <thead><tr><th>Últimos partidos</th></tr></thead>
                            {% for i in match.get_team1_matches %}
                                <tbody>
                                    <td>
                                        {{ i.team1 }} {{ i.team1_score }} - {{ i.team2 }} {{ i.team2_score }}
                                    </td>    
                                </tbody>
                            {% endfor %}
                        </table>
                    </div>
                    <div class="col">
                        <h5><b><u>{{ match.team2 }}</u></b></h5>
                        <br>
                        <table class="table">
                            <thead><tr><th>Últimos partidos</th></tr></thead>
                            {% for i in match.get_team2_matches %}
                                <tbody>
                                    <td>
                                        {{ i.team1 }} {{ i.team1_score }} - {{ i.team2 }} {{ i.team2_score }}
                                    </td>    
                                </tbody>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<script>
    window.onload = function(){
        document.getElementById('list_apuestas').style.background='#007bff';
        document.getElementById('list_apuestas').style.color= 'white';
    }
</script>

{% endblock %}

prode/templates/prode/apuestasOriginal.html
{% extends "prode/navigation.html" %}
{% load static %}
{% block content %}

{% include 'prode/messages.html' %}

{% for c in competitions %}
<h2 class="text-light text-center" style="font-family: serif">
    {{c.name}}
</h2>

<div class="lista-proximos-partidos text-center">
    
    <div class="row">
        
        <div class="col-md-6 offset-md-3">
            
            {% for match in matchs %}
            {% if c.name == match.competition.name %}
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="user_id" id="user_id" value="{{ user.id }}" formmethod="GET">
                    {% for bet in bets %}
                        {% if match.id == bet.match.id %}
                            <input type="hidden" name="bet_id" id="bet_id" value="{{ bet.id }}" formmethod="GET">
                        {% endif %}
                    {% endfor %}
                    <input type="hidden" name="match" id="match" value="{{ match.id }}">
                    <div class="card">
                        <h5 class="card-header" style="background: rgb(76, 167, 65)">{{ match.start|date:'d-m-Y' }}</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <img src="{{ '/static/' }}{{ match.team1.flag }}" alt="Bandera">
                                    <br>
                                    {{ match.team1.name }}
                                </div>
                                <div class="col">
                                    {{ form.team1_score }}
                                </div>
                                <div class="col">
                                    {{ form.team2_score }}
                                </div>
                                <div class="col">
                                    <img src="{{ '/static/' }}{{ match.team2.flag }}" alt="Bandera">
                                    <br>
                                    {{ match.team2.name }}
                                </div>
                            </div>
                        <button class="btn btn-primary" type="submit">Apostar</button>
                        </div>
                    </div>
            </form>
            <br>
            {% endif %}
            {% endfor %}
        
        </div>
    
    </div>    

</div>
<br>
{% endfor %}




<script>
    window.onload = function(){
        document.getElementById('list_apuestas').style.background='#007bff';
        document.getElementById('list_apuestas').style.color= 'white';
    }
</script>


{% endblock %}

prode/templates/prode/change_password.html
<form id="form-password" method="post" action="{% url 'prode:change_password' %}">
  {% csrf_token %}
    <!--OLD PASSWORD-->
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-sizing-default">Contraseña actual</span>
        </div>
        <input class="form-control form-control-sm" name="old_password" id="id_old_password" type="password" placeholder="Contraseña actual">
    </div>
    <br>

    <!--NEW PASSWORD 1-->
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-sizing-default">Nueva contraseña</span>
        </div>
        <input class="form-control form-control-sm" name="new_password1" id="id_new_password1" type="password" placeholder="Nueva contraseña">
    </div>    
    <br>

    <!--NEW PASSWORD 2-->
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-sizing-default">Repetir nueva contraseña</span>
        </div>
        <input class="form-control form-control-sm" name="new_password2" id="id_new_password2" type="password" placeholder="Repita nueva contraseña">
    </div>    
    <br>

    <button type="submit" class="btn btn-light text-info">Actualizar contraseña</button>
</form>

prode/templates/prode/grupos.html
{% extends "prode/navigation.html" %}
{% block content %}
<h1 class="text-center">En construcción</h1>

<script>
    window.onload = function(){
        document.getElementById('list_grupos').style.background='#28a745';
        document.getElementById('list_grupos').style.color= 'white';
    }
</script>
{% endblock %}

prode/templates/prode/login.html
 <form id="formulario" method="post" action="{% url 'prode:login' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label for="id_username">Usuario</label>
                <div>
                    <input type="text" class="form-control" name="username" maxlength="254" required id="id_username" autofocus />
                </div>
            </div>
            <div class="form-group">
                <label for="id_password">Contraseña</label>
                <div>
                    <input type="password" class="form-control" name="password" id="id_password" required />
                </div>
            </div>
        </div>
    </div> 
</form>

prode/templates/prode/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

prode/templates/prode/signup.html
<form id="formulario" method="post" action="{% url 'prode:signup' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label for="id_username">Nombre de usuario</label>
                <div>
                    <input class="username_validado form-control" type="text" name="username" maxlength="150" id="id_username" autofocus required/>
                </div>
            </div>
            <div class="form-group">
                <label for="id_first_name">Nombre</label>
                <div>
                    <input type="text" name="first_name" maxlength="30" id="id_first_name" class="form-control" required/>
                </div>
            </div>
            <div class="form-group">
                <label for="id_last_name">Apellido</label>
                <div>
                    <input type="text" name="last_name" maxlength="150" id="id_last_name" class="form-control" required/>
                </div>
            </div>
            <div class="form-group">
                <label for="id_email">Correo electrónico</label>
                <div>
                    <input type="email" name="email" id="id_email" class="form-control" required />
                </div>
            </div>    
            <div class="form-group">
                <label for="id_password1">Contraseña</label>
                <div>
                    <input type="password" name="password1" id="id_password1" class="form-control" required />
                </div>
            </div>
            <div class="form-group">
                <label for="id_password2">Repetir contraseña</label>
                <div>
                    <input type="password" name="password2" id="id_password2" class="form-control" required />
                </div>
            </div>
        </div>
    </div>
</form>